#!/usr/bin/bash

TEXT=$1
MEDIA_IDS=$2

RESOURCE="/1.1/statuses/update.json"
STATUS=$TEXT${MEDIA_IDS:+&media_ids=$MEDIA_IDS}

WORK_DIR=/here

docker run -v $PWD:$WORK_DIR \
           -w $WORK_DIR \
           twurl $RESOURCE \
                 -d "status=$STATUS"
