#!/usr/bin/bash

MEDIA_PATH=$1

HOST="upload.twitter.com"
RESOURCE="/1.1/media/upload.json"
WORK_DIR=/here

docker run -v $PWD:$WORK_DIR \
           -w $WORK_DIR \
           twurl $RESOURCE \
                 -X POST \
	             -H $HOST \
                 --file $MEDIA_PATH \
                 --file-field media \
